export const clientId = import.meta.env.VITE_CLIENT_ID
export const clientSecret = import.meta.env.VITE_CLIENT_SECRET
export const suggestions = [
  'Droeloe',
  'San Holo',
  'Duumu',
  'Taska Black',
  'Duskus',
  'Petit Biscuit',
  'Kasbo',
  'Shallou',
  'Slow Magic',
  'Odesza',
  'Flume',
  'Porter Robinson',
  'Madeon',
  'Illenium',
  'Seven Lions',
  'Said The Sky',
  'Trivecta',
  'Crystal Skies',
  'Last Heroes',
  'Nurko',
  'William Black',
  'Slander',
  'Adele',
  'Ed Sheeran',
  'Taylor Swift',
  'The Weeknd',
  'Ariana Grande',
  'Justin Bieber',
  'Dua Lipa',
  'Katy Perry',
  'Lady Gaga',
  'Shawn Mendes',
  'Selena Gomez',
  'Camila Cabello',
  'Halsey',
  'Zara Larsson',
  'Troye Sivan',
  'Lorde',
  'Lana Del Rey',
  'Billie Eilish',
  'Alessia Cara',
  'Bebe Rexha',
  'Miley Cyrus',
  'Rihanna',
  'Beyoncé',
  'Alicia Keys',
  'Christina Aguilera',
  'Jennifer Lopez',
  'Britney Spears',
  'Pink',
  'Kelly Clarkson',
  'Avril Lavigne',
  'Fergie',
  'Gwen Stefani',
  'Nelly Furtado',
  'Shakira',
  'Enrique Iglesias',
  'Ricky Martin',
  'Pitbull',
  'J Balvin',
  'Maluma',
  'Bad Bunny',
  'Ozuna',
  'Daddy Yankee',
  'Don Omar',
  'Wisin & Yandel',
  'Romeo Santos',
  'Prince Royce',
  'Marc Anthony',
  'Carlos Vives',
  'Juanes',
  'Thalía',
  'Paulina Rubio',
  'Gloria Trevi',
  'Alejandra Guzmán',
]
